modules/bash:
- changed-files:
  - any-glob-to-any-file: modules/bash/**
modules/checkov:
- changed-files:
  - any-glob-to-any-file: modules/checkov/**
modules/docker:
- changed-files:
  - any-glob-to-any-file: modules/docker/**
modules/docs:
- changed-files:
  - any-glob-to-any-file: modules/docs/**
modules/flake8:
- changed-files:
  - any-glob-to-any-file: modules/flake8/**
modules/git:
- changed-files:
  - any-glob-to-any-file: modules/git/**
modules/github:
- changed-files:
  - any-glob-to-any-file: modules/github/**
modules/make:
- changed-files:
  - any-glob-to-any-file: modules/make/**
modules/packages:
- changed-files:
  - any-glob-to-any-file: modules/packages/**
modules/readme:
- changed-files:
  - any-glob-to-any-file: modules/readme/**
modules/terraform:
- changed-files:
  - any-glob-to-any-file: modules/terraform/**
modules/tflint:
- changed-files:
  - any-glob-to-any-file: modules/tflint/**
modules/tfsec:
- changed-files:
  - any-glob-to-any-file: modules/tfsec/**
