name: auto-release (moneway)

on:
  push:
    branches: [master, main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get PR from merged commit to master
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: moneway/release-drafter@feature/calver-tmpl
        with:
          publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
