name: auto-label
on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto-label.yml
