name: Auto Assign Reviewers
on:
  pull_request:
    branches: [master, main]
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Auto-Assign Action
        uses: lkcozy/auto-assign-reviewer-by-issuer
        with:
          config: .github/reviewers.yml
          token: ${{ secrets.GITHUB_TOKEN }}
