name: auto-label
on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Auto-Assign Labels
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto-label.yml
